DROP TABLE IF EXISTS `book`;
CREATE TABLE `book` (
`id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
`name` VARCHAR(100) NOT NULL,
`author` VARCHAR(100) NOT NULL,
`category`VARCHAR(50) NOT NULL,
`overview` VARCHAR(255) NOT NULL,
`cover` VARCHAR(100) NOT NULL,
`thumbails` VARCHAR(100) NOT NULL,
`chapterQty` SMALLINT(6) NOT NULL,
`questionQty` SMALLINT(6) DEFAULT NULL,
`replyQty` SMALLINT(6) NOT NULL,
`readingQty` SMALLINT(6) NOT NULL,
`finishQty` SMALLINT(6) DEFAULT NULL,
`starQty` SMALLINT(6) DEFAULT NULL,
`editedQty` SMALLINT(6) DEFAULT NULL,
`createdId` SMALLINT(6) NOT NULL,
`createdName` SMALLINT(100) NOT NULL,
`createdTime` DATE NOT NULL,
`updatedTime` DATE NOT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
