
DROP TABLE IF EXISTS `question`;
CREATE TABLE `question` (
`id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
`name` VARCHAR(100) NOT NULL,
`bookId` SMALLINT(6) NOT NULL,
`originalId` SMALLINT(6) NOT NULL,
`version` SMALLINT(6) NOT NULL,
`content` VARCHAR(255) NOT NULL,
`tags` VARCHAR (100) DEFAULT NULL,
`starQty` SMALLINT(6) NOT NULL,
`voteQty` SMALLINT(6) NOT NULL,
`createdId` SMALLINT(6) NOT NULL,
`createdName` VARCHAR (100) NOT NULL,
`createdTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updatedTime` DATETIME DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO question(name, content, bookId) VALUES ('xxx', 'xxxxx', '1');